### ISSUE TITLE
Bug: mocking constructor called by object gives inconsistent results

### ISSUE THREAD

**Issue by sglasman** [mockk/mockk#214]
### Description

I'm trying to mock a class which appears as a private property in an object, and which is constructed when the object initializes. The situation is illustrated more or less minimally by the following code excerpt:

```
object ExampleObject {

    private val exampleClass = ExampleClass()
    fun getExampleProperty(): Int = exampleClass.exampleProperty
}

class ExampleClass {

    val exampleProperty: Int = 1
}

@RunWith(JUnit4::class)
class MockkExampleTest {

    @Before fun setup() {
        mockkConstructor(ExampleClass::class)
        every {anyConstructed<ExampleClass>().exampleProperty} returns 0
    }

    @Test fun test1() {
        assertEquals(0, ExampleObject.getExampleProperty())
    }

    @Test fun test2() {
        assertEquals(0, ExampleObject.getExampleProperty())
    }
}
```

### Expected Behavior

`test1()` and `test2()` should both pass or both fail when run in sequence, since they are identical and don't have any obvious side effects.

### Current Behavior

When the two tests are run in sequence, the first to run passes and the second fails.

#### Steps to Reproduce

You can find this code in the form of an Android Studio project at `https://github.com/sglasman/MockkExample`. Running the tests together in Android Studio will reproduce the problem.

**Comment by oleksiyp** [comment]
Reproduced in MockK 1.9

**Comment by LedanDark** [comment]
Any updates on this ? Having the  same issue where the first test does mock the class and second test function does not properly mock the class.

**Comment by jonathanlermitage** [comment]
Same issue here.  This is a blocker for me :(

**Comment by ktiniatros** [comment]
Hello,

I spent last couple of days to get familiar with the library's internals and see how we can tackle this.

I realised that anyConstructed refers to different mock instances every time you referenced a mocked constructor from different tests. This cannot work with kotlin object since they are singletons and keep the same reference.

I solved this by keeping the same constructor mock in the registry: https://github.com/mockk/mockk/pull/521
@oleksiyp if you find time, could you check my approach and see if it is safe to land this?
I added the test case of @sglasman and it works now; all the tests pass for me but we need your experience to doublecheck there are no other side effects.
