### ISSUE TITLE
Bug: class cast

### ISSUE THREAD

**Issue by oleksiyp** [mockk/mockk#219]
https://stackoverflow.com/questions/54073139/mockk-classcastexception-when-mocking-final-class-that-implements-multiple-int

**Comment by paulnuk** [comment]
Happy to provide a test case for this, test any fix if needed.

**Comment by oleksiyp** [comment]
Appreciate any help. Would be nice to have test without dependnecy to Spring

**Comment by paulnuk** [comment]
I've written a one line test along with a gradle file that reproduces the problem. It does have the Spring dependencies I'm afraid. I suspect the issue is around the fact that the code is using a chain of builders that return different sub-classes or implementations to what mockk is expecting. 

I'll try and have a proper look later.

[build.gradle.kts.txt](https://github.com/mockk/mockk/files/2746886/build.gradle.kts.txt)
[Tests.kt.txt](https://github.com/mockk/mockk/files/2746887/Tests.kt.txt)

**Comment by oleksiyp** [comment]
The problem here is that the template argument type is erased and not possible to recover. The only solution is to specify mock directly so that `reified` type will capture actual class:
```
    val mockk = mockk<HttpSecurity>(relaxed = true)
    val csrf = mockk.csrf()
    every { csrf.disable() } returns mockk(relaxed = true)
    val disable = csrf.disable()
    disable.headers()
```
