### ISSUE TITLE
Question: What is the difference between clearConstructorMockk and unmockkConstructor?

### ISSUE THREAD

**Issue by davidrpiper** [mockk/mockk#233]
I've been using `mockkConstructor` in some test setup methods, and `clearConstructorMockk` in teardowns. After some strange test failures, it appears that `clearConstructorMockk` was not doing what I expected, and I actually needed to use `unmockkConstructor` to remove the mocks to return the test setup to a clean slate.

What is the difference between `clearConstructorMockk` and `unmockkConstructor`?

**Comment by oleksiyp** [comment]
`clearConstructorMockk` removes all the associated state(which is probably not done due to some bug), `unmockkConstructor` untransforms the mock back and as well more aggressively remove all associated state.

Please if you want to help improve it submit simple reproducible code for the fail of `clearConstructorMockk`.
