### ISSUE TITLE
Bug: verifying a mock ()->Unit requires relaxed=true

### ISSUE THREAD

**Issue by robfletcher** [mockk/mockk#272]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

When mocking a lambda whose return type is `Unit` I should not have to supply an answer when using `relaxUnitFun = true`.

### Current Behavior

I have to use `relaxed = true` or the verification fails due to there being no answer.

### Failure Information (for bugs)

Attaching a debugger, I can see the `Invocation` type is a `Function1` with a return type of `Any`. Thus `MockKStub.shouldRelax` returns `false`. `MethodDescription.returnType` is `Any`, `MethodDescription.returnsUnit` is `false`.

#### Context

* MockK version: 1.9.2
* Kotlin version: 1.3.21
* JDK version: 8
* JUnit version: 5.4.0

#### Minimal reproducible code (the gist of this issue)

https://gist.github.com/robfletcher/7c67b728e1c657f1b03ca6303b0f67af

**Comment by oleksiyp** [comment]
Thanks for the detailed report

**Comment by Raibaz** [comment]
The issue here seems to be that the `Invocation` object being passed to `defaultAnswer` contains a method that has `returnsUnit == false`, so the check `relaxUnitFun && invocation.method.returnsUnit` inside `MockKStub.shouldRelax()` returns false.

The reason why the method has `returnsUnit == false` seems to be that the method being intercepted as the `@Origin` by the `JvmMockKProxyInterceptor` has returnType `java.lang.Object.

Should we implement a specific advice for lambdas that takes care of handling the case where they return Unit?

**Comment by serandel** [comment]
I just hit this bug, I'm glad to see it's not stale anymore.

**Comment by Teja-Konjeti** [comment]
@Raibaz Can you please fix this? Need this going as many of my functions return Unit..

**Comment by Raibaz** [comment]
I have been digging a bit into this, and seems like there's no way to implement an advice for lambdas as I was imagining earlier.

As discussed in several places by the Bytebuddy maintainer ([here](https://stackoverflow.com/questions/33912026/intercepting-calls-to-java-8-lambda-expressions-using-byte-buddy), [here](https://stackoverflow.com/questions/63415289/calling-lambda-from-an-intercept-method-with-bytebuddy-raises-java-lang-noclassd) and [here](https://github.com/raphw/byte-buddy/issues/80), for instance), intercepting lambdas with Bytebuddy is no easy feat, because lambdas, technically, are not really members of a class, but they are loaded with a different classloader altogether.

As far as I can tell, then, even if a lambda can intercepted (which it is, even in mockk), there is no way to access the description of the lambda itself, because it's resolved to an `invoke` method of a generated class that takes an Object and returns an Object.

This being said, I'm by no means a Bytebuddy expert, so maybe @oleksiyp has some better insights on this.

**Comment by oleksiyp** [comment]
@Raibaz thanks for exploring this issue. Dont have any addition here. Belive it is true that there are some limits mockk can't go beyond. We should accept that.
