### ISSUE TITLE
Cannot mock function named `fun get(string: String): String`

### ISSUE THREAD

**Issue by guelo** [mockk/mockk#405]
When trying to mock a function named `fun get(string: String): String` the `get` function referred to inside the `every` block is actually the extension function  `operator fun Any.get(name: String) = DynamicCall(this, name, { any() })` defined in MockKMatcherScope.

Test case:
 
```kotlin
import io.mockk.every
import io.mockk.mockk
import org.junit.Test

class UnderTest {
    fun get(string: String) = "xyz"
}

class Test {
    @Test
    fun test() {
        mockk<UnderTest> { every { get("def") } returns "abc" }
    }
}
```
Produces  compiler error on the "abc" string:
> Type mismatch: inferred type is String but MockKMatcherScope.DynamicCall was expected

**Comment by fabiobauer** [comment]
Hey @guelo,

the problem with your code is that your using the "wrong" get-Function.

Mockk uses operator overloading (in particular an Indexed access operator) to establish an easy access to mocked methods. This is achieved by defining an **get-Function** in the **MockKMatcherScope**.
 `operator fun Any.get(name: String) = DynamicCall(...)` 

When using `every { ... }`, you define an lambda in the scope of **MockKMatcherScope**, therefore by calling `get("def")` you're actually call the **get-Function** from the Library and not your own one.

You can simply fix this by specifying the right context:
```
mockk<UnderTest>() {
    every { this@mockk.get("def") } returns "abc"
}
```

or with variables

```
val myMock = mockk<UnderTest>()
every { myMock.get("def") } returns "abc"
```

**Comment by guelo** [comment]
I hope when stale bot marks this issue as closed it will still show up in google results because @fabiobauer's solution would probably help people.

**Comment by guelo** [comment]
Or maybe we should move this to stackoverflow

**Comment by oleksiyp** [comment]
I think it is enough to just close it. This is how usually things happen on other open-source projects. 

It's hard to guarantee that people with the same problem will easily find it because of many various reasons, even if it is opened. If you really want to help the community the best would be to write a separate Stack Overflow question. Thanks!

**Comment by icorbrey** [comment]
Unfortunately, both of @oleksiyp's solutions do not work for me when working with `coEvery`. I'm trying to mock the use of `io.ktor.client.HttpClient` as follows:

```kotlin
val httpClient = mockk<HttpClient>()
coEvery { httpClient.get("https://this.is/a/test") } returns TestResource()
```

`TestResource` is simply a test data structure I created. I get the following error when I try to do this:

```
Type mismatch.
Required: MockKMatcherScope.DynamicCall
Found:    TestResource
```

I've also tried grabbing a reference to the correct `get` method (with `(httpClient::get)( ... )`), but since `get` is both a member and an extension it doesn't work out. Additionally, calling `httpClient["get"]( ... )` compiles just fine, but then I get the following error: 

```
io.mockk.MockKException: can't find function get( ... ) for dynamic call
```

Any ideas?

**Comment by icorbrey** [comment]
So I got around that issue by specifying the type parameter, but now the type information gets erased. I've tried adding `.hint(TestResource::class)` both before and after the `get` method call, but neither works.

**Comment by frevib** [comment]
@icorbrey did you get around this issue?

**Comment by hardik-trivedi** [comment]
Hello this issue cannot be treated as close. This still persist and creates issue while using it with ktor.
ktor has a get function and if you want to call this get function on mocked ktor `HttpClient` class it doesn't identify and refer to mockk's internal Any.get function. 

e.g.

`coEvery { coreHttpEngine.get("https://something.com/v2/countries") } returns listOf(countryIndia)`

This will result into 

```
Type mismatch.
Required:
MockKMatcherScope.DynamicCall
Found:
List<CountryItem>
```

**Comment by mecoFarid** [comment]
@hardik-trivedi Looks like no one gives a sh*t about it. This is really a huge problem even though there is a workaround

**Comment by mecoFarid** [comment]
@fabiobauer How did you even got it working? People still say your solution is not working or was it just a hypothetical solution?

**Comment by fabiobauer** [comment]
Hey @mecoFarid, 

my example from above was tested back then and as far as I can tell this method is still functioning. However, it is important to note that the original issue was **not** related to **Coroutines**! The problem is not completely solved here and the issue should be reopened. (fyi @oleksiyp & @Raibaz)

For an interim solution, this might help on the KTOR-Client side: https://ktor.io/docs/http-client-testing.html#test-client

**Comment by mecoFarid** [comment]
@fabiobauer I am actually using it on Map not Ktor and even that did not work. Looks like some internal library change made this workaround obsolete

**Comment by slaha** [comment]
In my case, the `operator fun get(key: String)` was an extension. I was able to mock the function using import alias and mock the aliased function:

```kotlin
import foo.bar.baz.get as getSomething
…
@MockK
private lateinit var baz: Baz
…
every { baz.getSomething("KEY") } returns "VALUE"
```

But for member functions, the issue still persists.
