### ISSUE TITLE
In a coroutine context, stubbing after instantiation can fail

### ISSUE THREAD

**Issue by ArchangelX360** [mockk/mockk#493]
### ~Expected Behavior~ this is more a question than a bug

Running this test:

```kotlin
import io.mockk.coEvery
import io.mockk.mockk
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.async
import kotlinx.coroutines.runBlocking
import org.junit.Test

class Producer {
    fun produce() = 123
}

class Consumer(private val producer: Producer) {
    private var initialValue = GlobalScope.async { producer.produce() } // this call is the important one

    suspend fun consume() {
        initialValue.await()
    }
}

class SomeTest {
    @Test
    fun `produce is not mocked for some reason`() = runBlocking {
        val producer: Producer = mockk()
        // If the stubbing is done before the instantiation of `Consumer`, then it works
        // coEvery { producer.produce() } returns 33

        val consumer = Consumer(producer)
        coEvery { producer.produce() } returns 33

        consumer.consume()
    }
}
```

will produce:
```
no answer found for: Producer(#1).produce()
io.mockk.MockKException: no answer found for: Producer(#1).produce()
```

The stubbing being done after `Consumer` is instantiated and `producer.produce()` being defined in the GlobalScope, the stub is not replacing the call to `produce()`.

Is this expected? If so, is there any way to workaround the issue? For now, I basically just reworked my code to ensure the stubbing was done prior to the injection of `Producer` to `Consumer`, but I was curious if there was another solution to that.

#### Context

* MockK version: 1.10.0
* OS: MacOS
* Kotlin version: 1.4.0
* JDK version: 14
* JUnit version: 5
* Type of test: unit test

**Comment by Raibaz** [comment]
I think the behavior you're experiencing is to be expected: even if `producer.produce` is executed asynchronously, it's still being called when you instantiate the Consumer object, which is when Mockk tries to determine what to answer when it runs.

So, in the end, yes, you have to describe your expected answer before executing `producer.produce`.

A possible alternative would be to mock the Producer with `relaxed = true`: that would spare you from having to describe the expected answer, because you would get a default answer (0, in this case, since `produce` is returning an Int).

Does this make sense to you?

**Comment by ArchangelX360** [comment]
Makes sense, thanks!
