### ISSUE TITLE
mockkConstructor still calls constructor

### ISSUE THREAD

**Issue by tylerlofgren** [mockk/mockk#515]
### Expected Behavior
When a class has its constructor mocked via mockkConstructor(YourClass::class) then code within that constructor should not actually be ran. I would only expect that a mock object would be returned.

### Current Behavior

Code within the main constructor is still ran.

```
class MockkConstructorTest : BehaviorSpec({

    Given("an idea") {
        When("prove it") {
            println("starting")
            class Dummy {
                init {
                    println("within constructor")
                }

                fun something(): String {
                    return "real"
                }
            }
            mockkConstructor(Dummy::class)
            every { anyConstructed<Dummy>().something() } returns "fake"
            println(Dummy().something())
            println("done")
        }
    }
})
```

Output: 

> starting
within constructor
fake
done

#### Context

* MockK version: 1.10.0
* OS: macOS Catalina 10.15.7
* Kotlin version: 1.4.0
* JDK version: 11.0.7
* Kotest version: 4.2.5
* Type of test: unit test

**Comment by Raibaz** [comment]
I have been digging a bit into the code and looks like this is intentional.

According to the [doc](https://mockk.io/#constructor-mocks) (emphasis mine), 

> The basic idea is that **just after the constructor of the mocked class is executed** (any of them), objects become a constructed mock. Mocking behavior of such a mock is connected to the special prototype mock denoted by anyConstructed<MockCls>().

Not 101% sure about the reason why, but my personal guess is that for an object instance to be constructed you actually need to execute _some_ constructor. 

This being said, I imagine you don't want your constructor to be executed because of some side effects inside it that you don't want to happen: IMHO, if this is your case, you should at least provide a constructor with no side effects that just constructs an object.

**Comment by romrell4** [comment]
> I have been digging a bit into the code and looks like this is intentional.
> 
> According to the [doc](https://mockk.io/#constructor-mocks) (emphasis mine),
> 
> > The basic idea is that **just after the constructor of the mocked class is executed** (any of them), objects become a constructed mock. Mocking behavior of such a mock is connected to the special prototype mock denoted by anyConstructed().
> 
> Not 101% sure about the reason why, but my personal guess is that for an object instance to be constructed you actually need to execute _some_ constructor.
> 
> This being said, I imagine you don't want your constructor to be executed because of some side effects inside it that you don't want to happen: IMHO, if this is your case, you should at least provide a constructor with no side effects that just constructs an object.

Thanks for digging! However, this doesn't help when it's a constructor that you don't own (e.g. Android platform constructors)

**Comment by janspoerer** [comment]
I am facing issues with this behavior as well. Is there now an option to make an object a constructed mock **before** the constructor is called, and to **avoid** the constructor call altogether? 

In my case, the constructor of the mocked object throws an error and I cannot change the method I'm testing, and I cannot change the constructor of the object.

The object being mocked is pretty complex. It is similar to a database pointer that directly needs to establish an authenticated connection upon being constructed.

**Comment by codepushr** [comment]
I have to agree. I'm trying hard to mock around a class that constructs bluetooth specific objects (managers, adapters...). I'm not sure how this can be achieved with how mockkConstructed works as of now.

**Comment by ghilainm** [comment]
@romrell4 Totally agree, in my specific case we are using data classes with constructor imlpementing validation logic. I don't want this logic to be executed when testing mappers and I don't want to provide any other default constructor.

**Comment by YSakhno** [comment]
> Not 101% sure about the reason why, but my personal guess is that for an object instance to be constructed you actually need to execute _some_ constructor.

This reasoning is sound, but it does not hold water, because `mockk<MyClass>()` returns a mock instance without executing _any_ constructor.

Why cannot the mocked constructors effectively create the same thing as function `mockk` does, is beyond me... Without such functionality we need to create private methods like

```kotlin
    private fun createMyClass() = MyClass()
```

and mock those (assuming we _can_ modify the code that constructs `MyClass`, which is not always the case).
