### ISSUE TITLE
Remove ndk.dir deprecation warning

### ISSUE THREAD

**Issue by Raibaz** [mockk/mockk#654]
```
WARNING: NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [20.0.5594570] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
```

**Comment by agebhar1** [comment]
Hello @Raibaz,

I had a look for the warning text and found the hint on [Androids Studio Release notest](https://developer.android.com/studio/releases?utm_source=android-studio#4-0-0-ndk-dir). Indeed [local.properties](https://github.com/mockk/mockk/blob/9fe07a57dd73a4f2b0ad2a4cacc851b9d6fc1f76/matrix/local.properties#L11) contains the variable.

Maybe I did something wrong but I can't find the warning in the last successful builds/test of Android [android-instrumented-tests (28)](https://github.com/mockk/mockk/runs/2960418443?check_suite_focus=true) and [android-instrumented-tests (29) ](https://github.com/mockk/mockk/runs/2960418491?check_suite_focus=true).

I can give them a try to fix/remove the warning.

**Comment by Raibaz** [comment]
Sure, go for it.

**Comment by agebhar1** [comment]
I will.

**Comment by agebhar1** [comment]
Hello @Raibaz,

after had a deeper look into the issue the solution is quite simple. In https://github.com/mockk/mockk/blob/9473e79d1b4fa99c91d87144557cacf167f29e64/gradle/detect-android-sdk.gradle#L15-L20 which is applied from `settings.gradle` the code tries to detect the properties file `local.properties` from the root of the project. If it's found the whole content is loaded as properties. The file itself is ignored by `.gitignore`.

If it does not exists either `$ANDROID_HOME`, `$ANDROID_SDK_ROOT` or `${HOME}/Android/Sdk` must point to a valid Android environment. If so, the warning does not appear and `local.properties` is generated. On my local machine it's:
```
#generated by 'detect-android-sdk.gradle'
#Thu Jul 08 13:03:23 CEST 2021
sdk.dir=/usr/local/lib/android/sdk
```

If `local.properties` contains the `ndk.dir` property
```
#generated by 'detect-android-sdk.gradle'
#Thu Jul 08 13:03:23 CEST 2021
ndk.dir=/usr/local/lib/android/sdk/ndk/21.1.6352462
sdk.dir=/usr/local/lib/android/sdk
```
, the warning is presented on the command line:
```
> Configure project :mockk-agent-android
WARNING: NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.1.6352462] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
NDK was located by using ndk.dir property. This method is deprecated and will be removed in a future release. Please delete ndk.dir from local.properties and set android.ndkVersion to [21.1.6352462] in all native modules in the project. https://developer.android.com/r/studio-ui/ndk-dir
```

The GitHub Action runs didn't show the warning because the properties file is not present and both contains the required environment variable which points to an Android installation.

https://github.com/actions/virtual-environments/blob/ubuntu20/20210628.1/images/linux/Ubuntu2004-README.md
https://github.com/actions/virtual-environments/blob/macOS-10.15/20210626.1/images/macos/macos-10.15-Readme.md

One have to remove the property `ndk.dir` from `local.properties` and the build should be fine without the warning.

**Comment by Raibaz** [comment]
Got it, thanks a lot for investigating this, this can safely be closed then.
