### ISSUE TITLE
Question: does mockkConstructor not work for Java class?

### ISSUE THREAD

**Issue by andreas-trvlk** [mockk/mockk#660]
I created a method that instantiates new class. I used `mockkConstructor`, but the real constructor is still called.

**Comment by Raibaz** [comment]
Can you please provide sample code of the issue you are experiencing?

**Comment by andreas-trvlk** [comment]
I can only give you the approximation because the code is for internal use only. FYI, it is written for Spring Boot project. I think it should not matter.

```kotlin
// =============Class to be Tested============
@Configuration
class SomeConfiguration(
   private val someVal: String
) {
   @Bean 
   fun createComponent() : JavaComponent {
       return JavaComponent(someVal)
   }
}
// ==============Unit Test================
class SomeConfigurationTest {
    private lateinit var configuration: SomeConfiguration

    @BeforeEach
    fun setUp() {
        configuration = SomeConfiguration("RandomString")
    }

    @AfterEach
    fun afterTest() {
        clearAllMocks()
    }

    @Test
    fun `Test createComponent() - when invoked - then should create object`() {
         // arrange
         mockkConstructor(JavaComponent::class) // not working, real constructor is still invoked.

         //act
         configuration.createComponent()
    }
}
```

**Comment by Raibaz** [comment]
Ok I see what you mean now.

This looks like a duplicate of #515.

As I was mentioning there, it's not possible to entirely replace a constructor invocation: when you instantiate an object, _some_ constructor still needs to be invoked for the instance to be created.

**Comment by janspoerer** [comment]
I would like to ask a question to better understand the utility of `mockkConstructor`. As I understand it from [this guide](https://notwoods.github.io/mockk-guidebook/docs/mocking/constructor/), `mockkConstructor` will call the original constructor upon the first constructor call, and then always use the constructed instance instead of creating new instances (singleton). Therefore, I suppose that **tests can run faster.**

**Is there any other benefit in addition to the runtime speedup?**

I am facing issues with this behavior as well. It's unfortunate that this cannot technically be changed. Even more reason to write solid, easily testable code to begin with.

In my case, the constructor of the mocked object throws an error and I cannot change the method I'm testing, and I cannot change the constructor of the object.

The object being mocked is pretty complex. It is similar to a database pointer that directly needs to establish an authenticated connection upon being constructed.
