### ISSUE TITLE
Sponsorship question

### ISSUE THREAD

**Issue by GonMMarques** [mockk/mockk#742]
Hello,

I noticed that you have sponsoring enabled (through Open Collective) but would you be open to having GitHub Sponsors (directly) as a sponsoring opportunity?

Thanks in advance.

**Comment by Raibaz** [comment]
I definitely have nothing against it, but perhaps it'd be better to get a comment from @oleksiyp, as the choice to go with Open Collective was his at the time :)

**Comment by oleksiyp** [comment]
Ofc no problem to have GitHub sponsorship... I just need to understand how
it is possible to use this money afterwards (in sense of
taxes/transfers/law)

Actually, for me, the bigger problem is how to spend this money :-)  I
spent only twice to continue domain name reservation... and that's it.

Happy to hear any ideas about spending :-) One more idea is to pay for bug
fixes/issues... but what stops me is that probably we have not that big
income flow, but maybe I am wrong and the expertise required is pretty
significant.


чт, 11 нояб. 2021 г. в 10:23, Mattia Tommasone ***@***.***>:

**Comment by GonMMarques** [comment]
Hello again,

Thanks for the reply, maybe this clarifies a bit https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors the receiving of the sponsorship

**Comment by oleksiyp** [comment]
I checked the conditions... looks clear, except for how I should pay taxes. In the case of the open collective they take this aspect by registering "non-profit org" and administering it.  And here they just say "we take all responsibility to pay taxes", but tbh still have doubts about what exactly this means.

From my point of view, I am ready to set up an account and collect money for the future, but tbh I would be a lot happier if we as well find a good application to collect money (to invest them into something useful and, yes, raise more money 😈 ). If we have a clear goal that would be a lot more motivating to collect them (and pay taxes 😄), as well as easier communication and transparency for contributors.

My dream some time ago when I started collecting to hire a few devs to resolve issues on a paid basis... I was looking at some JS projects and their professional approach to engineering and they were funded solely by the open collective, and was thinking it might be nice to organize something similar. But maybe this is the wrong direction to go due to several reasons.

Maybe there is some unexpected way we can spend collected funds. For, example, for creating an IntelliJ IDEA plugin (as a freelance job). Or investing in merch T-Shirts shop (speaking sarcastically) or maybe order more quality content on YouTube or as an article. I will keep thinking about what might be a great thing at this moment.

In extreme case, nothing bad happens if we have just paid domain for 20 years 😄
