### ISSUE TITLE
Verify bundleOf on function params

### ISSUE THREAD

**Issue by Dalakoti07** [mockk/mockk#787]
### Prerequisites
I have a fragment whose method A would called when livedata is set and last param of method A is bundle. I am using verify to assert this. But equal matcher is returning false. Following image shows how assertion is done
![image](https://user-images.githubusercontent.com/38468299/152769910-0d120a0d-ba07-4cb0-9d76-8eefe1c308a1.png)

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
verify should work fine. In below screenshot we have 
![image](https://user-images.githubusercontent.com/38468299/152769834-d5e3a91a-a152-4b7b-9fff-c807c0c66e73.png)

### Current Behavior
Test assertion is failing

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.2
* OS: Mac OS M1 chip
* Kotlin version: 1.5.31
* JDK version: JavaVersion 11
* JUnit version: 4.13.2
* Type of test: android instrumented test with robolectric

#### Failure Logs
![image](https://user-images.githubusercontent.com/38468299/152769834-d5e3a91a-a152-4b7b-9fff-c807c0c66e73.png)

#### Stack trace

```
Verification failed: call 1 of 1: class com.something.consumer.utils.extensions.NavigationExtensionsKt.navigateToDestination(eq(LoginFragment{4639bef5} (28703e02-cb27-4571-a04b-4789ce9936d6 id=0x1020002 tag=)), eq(2131297347), eq(2131296366), eq(Bundle[{mobile=9988776655}]), null(), null())). Only one matching call to NavigationExtensionsKt(static NavigationExtensionsKt)/navigateToDestination(Fragment, Int, Int, Bundle, NavOptions, Extras) happened, but arguments are not matching:
[0]: argument: LoginFragment{4639bef5} (28703e02-cb27-4571-a04b-4789ce9936d6 id=0x1020002 tag=), matcher: eq(LoginFragment{4639bef5} (28703e02-cb27-4571-a04b-4789ce9936d6 id=0x1020002 tag=)), result: +
[1]: argument: 2131297347, matcher: eq(2131297347), result: +
[2]: argument: 2131296366, matcher: eq(2131296366), result: +
[3]: argument: Bundle[{mobile=9988776655}], matcher: eq(Bundle[{mobile=9988776655}]), result: -
[4]: argument: null, matcher: null(), result: +
[5]: argument: null, matcher: null(), result: +
```

**Comment by Raibaz** [comment]
I don't know the internals of the `Bundle` class, but what the stack trace is telling you is that it tried to match the bundle being used as a parameter to your `navigateToDestination` function with `paramsBundle` using `Bundle.equals`, and it returned false for those two objects.

If you are interested in just confronting the `mobile` property rather than verifying that the bundle being passed `equals` the one in your test, you can write your verification like this:

```
verify {
    sutFragment.navigateToDestination(
        R.id.otpFragment,
        R.id.action_loginFragment_to_otpFragment,
        match { it.mobile == "9988776655" }
    )
}
```

This way, the matching will be performed only on the `mobile` property.

Alternatively, you can use a [slot](https://mockk.io/#capturing) to capture the value being passed and then perform assertions on it.
