### ISSUE TITLE
Suggestion: Recommendations for running parallel tests

### ISSUE THREAD

**Issue by sharmando** [mockk/mockk#860]
I think it would be useful to add a section about running mock with parallel test execution.

I understand now that clearAllMocks is not compatible with parallel tests as it will clear mocks across tests but I was confused about the behavior for a couple of days.

I am using mockk<> coEvery and coVerify with no issues. But if some areas of mockk are not threadSafe or not recommended for parallel test execution that could also be discussed in the parallel execution section.

**Comment by nilajasp** [comment]
mockkObject is also not threadsafe?

**Comment by aiguofer** [comment]
I'm interested in this as well. We want to have fast tests, so we need to run in parallel. We've been creating classes just to wrap functions for the sake of mocking. IMO, we should be using top level functions, but the inability to use `mockkStatic` in parallel is preventing us from doing so.

If there's a (future) paradigm where we can run these tests in parallel, I can convince my team on giving up parallel tests for now so we can use all the language features. Otherwise, we're having to give up functionality because of testing, which seems like a huge loss.

**Comment by aiguofer** [comment]
Seems like others have also been experiencing related issues: #1062

**Comment by milgner** [comment]
Probably `mockkConstructor` is affected as well. I was just investigating an issue with some flakyness when running tests in our CI environment when I noticed this issue. After disabling parallel execution, the test suite went back to green.

**Comment by Spirarel** [comment]
This is known and I guess just accepted behavior https://github.com/mockk/mockk/issues/301#issuecomment-492512079

Leads to some wicked bugs, when not expected.

**Comment by cies** [comment]
Should there not be a static mock scope, where we define the mock'ed static method/object/etc to only exist withtin a scope. Doing `mockkObject` and then `unmock` feels like a old way of doing things in the Kotlin reality of scopes/blocks/lambdas.

**Comment by xzhang-brex** [comment]
I'm trying to add multi-threading support to clearAllMocks, please review, thanks: https://github.com/mockk/mockk/pull/1276
