### ISSUE TITLE
Preferred style for mocking unit functions?

### ISSUE THREAD

**Issue by jamesonwilliams** [mockk/mockk#949]
MockK gives a number of ways to mock a unit function.

Let's suppose we have an interface like this:

```kotlin
interface Widget {
  fun spin()
}
```

There are at least 5 ways to mock the behavior of `spin()` on a `val widget = mockk<Widget>()`:

```kotlin

// Fluent ways
every { widget.spin() } just runs
every { widget.spin() } just Runs 

// Less elegant ways
every { widget.spin() } answers {}
every { widget.spin() } returns Unit

// Concise way
justRun { widget.spin() }
```

**Questions**:
1. Are there any technical differences to note between them, or are they all truly the same?
2. Which is the preferred style of the project maintainers?

**Comment by Raibaz** [comment]
1) They are basically the same; there may be some very slight differences in the implementations, but in terms of semantics and performances I'd say they are all equivalent.

2) I personally like what you refer to as "fluent ways", because I find them consistent with mocks for functions that return a value, e.g. `every { widget.computeValue() } returns 2` but they also differ slightly indicating more explicitly that there is no value returned from the function being mocked.

This being said, you are free to use whatever way you like, because of answer 1) :)
