### ISSUE TITLE
Which dependency should I use as a library author

### ISSUE THREAD

**Issue by jnizet** [mockk/mockk#982]
Hello. 

I'm the maintainer of SpringMockK.

Spring Boot 3 just came out, and I'd like to release a new version of SpringMockK, based on Java 17, Spring Boot 3, and the latest MockK version.

The documentation says that I should use `io.mockk:mockk:${mockkVersion}` to use MockK with gradle, and that I should use `<artifactId>mockk-jvm</artifactId>` to use MockK with Maven.

SpringMockK is *built* with gradle, but releases a Maven POM to Maven central, which defines a dependency on MockK. And of course, some people use SpringMockK with Gradle and others with Maven. So, which artifact ID should I use in the library? `mockk`, or `mockk-jvm`

Thanks in advance.

**Comment by aSemy** [comment]
If you're using Gradle you can use `io.mockk:mockk:${mockkVersion}`. If you're using Maven you have to specify the target variant by appending `-jvm`, so use `io.mockk:mockk-jvm:${mockkVersion}`.

**Comment by jnizet** [comment]
Thanks aSemy. The thing is, the question is about using it as part of a library, not an application. I thus have a dependency on mockk in the pom that I will *release*. And this pom will be used by gradle users and also by Maven users. So what should I use?

**Comment by aSemy** [comment]
Ah I see, I misunderstood. Thanks for explaining further.


Since you're using Gradle, and since MockK only has a JVM variant, and since you want to make it easy for Gradle and Maven users, then define an api dependency on `io.mockk:mockk-jvm:$mockkVersion`. This will work for both Gradle and MockK users.

To explain a little more, `mockk`/`mockk-jvm` aren't synonymous in Maven because Gradle publishes [additional information](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html) as well as a traditional Maven POM. The module metadata for `io.mockk:mockk` lists the variants, and their locations. Maven can't access the Gradle metadata, so when it sees `io.mockk:mockk`, it only reads the POM, which is effectively a dead-end.

Some other libraries add [additional Gradle config](https://github.com/Kotlin/kotlinx.serialization/blob/dc950f5098162a3f8dd742d04b95f9a0405470e1/gradle/maven-metadata.gradle#L27-L33) to specifically add `-jvm` variants to the unflavoured POM, so Maven can find its way. Perhaps MockK could do the same...

**Comment by jnizet** [comment]
Thanks @aSemy
